error_on_line_overflow = false
format_strings = false
reorder_imports = true
reorder_imported_names = true
report_todo = "Always"
report_fixme = "Always"
normalize_comments = true
use_try_shorthand = true
max_width = 110
