sudo: required
dist: trusty
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
cache:
  directories:
      - .vagga/nightly-home/.cargo
      - .vagga/nightly-home/.rustup
      - .vagga/.cache
before_script:
- 'echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml'
- 'echo alpine-mirror: http://mirrors.gigenet.com/alpinelinux/ >> ~/.vagga.yaml'
- 'echo cache-dir: $(pwd)/.vagga/.cache >> ~/.vagga.yaml'
- |
  echo "$(id -un):100000:65536" | sudo tee /etc/subuid | sudo tee /etc/subgid
  sudo apt-get install uidmap -y
  curl http://files.zerogw.com/vagga/vagga-install.sh | sh
script:
- vagga check-fmt
- vagga build
- vagga clippy
before_deploy:
- vagga doc
- vagga --use-env=GH_TOKEN doc_upload
