language: rust
addons:
    apt:
        sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9' ]
        packages: [ 'clang-3.9' ]

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
- cargo build
- cargo build --features gen
- diff -q input-sys/src/gen.rs $(find target -name gen.rs)
