language: rust
addons:
    apt:
        sources: [ 'ubuntu-toolchain-r-test' ]
        packages: [ 'gcc-5', 'libudev-dev' ]

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
  directories:
    - $HOME/.cargo

before_install:
- wget http://llvm.org/releases/4.0.0/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
- tar xf clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz

script:
- cargo build
- env LIBCLANG_PATH=`pwd`/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/lib CLANG_PATH=`pwd`/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang cargo build --features "gen"
- diff -t -w input-sys/src/gen.rs $(find target -name gen.rs)
