[package]
name = "input"
description = "libinput bindings for rust"
license = "MIT"
documentation = "https://Drakulix.github.io/input.rs"
repository = "https://github.com/Drakulix/input.rs"
version = "0.3.0"
keywords = ["wayland", "input", "bindings"]
categories = ["external-ffi-bindings"]
authors = ["Drakulix (Victor Brekenfeld)"]

[dependencies]
input-sys = { version = "1.7.1", path = "./input-sys" }
libc = "0.2"
bitflags = "1.0.0"

[features]
gen = ["input-sys/gen"]
