[package]
name = "input"
description = "libinput bindings for rust"
license = "MIT"
documentation = "https://Drakulix.github.io/input.rs"
repository = "https://github.com/Drakulix/input.rs"
version = "0.1.1"
keywords = ["wayland", "input", "bindings"]
categories = ["external-ffi-bindings"]
authors = ["Drakulix (Victor Brekenfeld)"]

[dependencies]
input-sys = { version = "1.7.0", path = "./input-sys" }
libc = "0.2"
