[package]
name = "input-sys"
version = "1.15.0"
authors = ["Victor Brekenfeld (Drakulix) <github@drakulix.de>"]
build = "build.rs"
description = "Bindgen generated unsafe libinput wrapper"
documentation = "https://drakulix.github.io/input.rs/input-sys"
repository = "https://github.com/Drakulix/input.rs/tree/master/input-sys"
keywords = ["wayland", "input", "bindings"]
categories = ["external-ffi-bindings"]
license = "MIT"
exclude = [".travis.yml", ".rustfmt.toml"]

[lib]
path = "src/lib.rs"

[build-dependencies]
bindgen = { version = "0.31", optional = true }

[dependencies]
libc = "0.2"

[features]
default = ["libinput_1_15"]
gen = ["bindgen"]
libinput_1_11 = []
libinput_1_14 = []
libinput_1_15 = []